"""Application-owned contracts implemented by outer adapters."""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Protocol

from app.domain.models import Intervention, Scenario


class Simulator(Protocol):
    def version(self) -> str: ...

    def run(
        self,
        scenario: Scenario,
        intervention: Intervention,
        seed: int,
        factor: float = 1,
        playback: bool = False,
    ) -> dict: ...


class ToolGateway(Protocol):
    async def call(self, name: str, arguments: dict) -> dict: ...

    async def schemas(self) -> list[dict]: ...


@dataclass
class ChatResponse:
    stop_reason: str
    content: list[dict]


class ChatModel(Protocol):
    async def complete(
        self, *, system: str, tools: list[dict], messages: list[dict]
    ) -> ChatResponse: ...


CityFetcher = Callable[[str, dict | None], tuple[list[dict], dict]]
RawSink = Callable[[dict, list[dict]], None]


class DisruptionStore(Protocol):
    """Public persistence contract; neither SQL nor connection types cross this port."""

    def display_path(self) -> str: ...

    def get_meta(self, key, default=None) -> Any: ...

    def set_meta(self, key, value) -> None: ...

    def version(self) -> str: ...

    def start_run(self, job, dataset_key, dataset=None) -> int: ...

    def finish_run(self, run_id, status, meta=None, inserted=0, updated=0, error=None) -> None: ...

    def runs(self, limit=50) -> list[dict]: ...

    def latest_successful_runs(self) -> dict: ...

    def upsert_incidents(self, records, source, raw_by_uid=None, seen_utc=None) -> tuple[int, int]: ...

    def record_live_sightings(self, uids, seen_utc=None) -> None: ...

    def incident_records(self, since_local=None, until_local=None) -> list[dict]: ...

    def query_incidents(self, filters, since_local=None, until_local=None, limit=100) -> tuple[int, list[dict]]: ...

    def max_incident_start(self, source) -> str | None: ...

    def upsert_closures(self, records, raw_by_uid=None, full_feed=True, seen_utc=None) -> tuple[int, int, int]: ...

    def closure_records(self) -> list[dict]: ...

    def add_travel_times(self, observations, fetched_utc=None) -> int: ...

    def travel_times(self, corridor="", segment="", since_local="", limit=500) -> list[dict]: ...

    def put_reference(self, name, rows, sha256=None) -> None: ...

    def get_reference(self, name) -> tuple[list[dict] | None, str | None]: ...

    def save_prediction(self, origin, selection, result) -> int: ...

    def predictions(self, limit=20) -> list[dict]: ...

    def start_sim(
        self, run_id, scenario, origin="manual", intersection_key=None, log_path=None
    ) -> Any: ...

    def add_sim_action(self, run_id, seq, event) -> None: ...

    def finish_sim(self, run_id, result, summary=None) -> None: ...

    def fail_sim(self, run_id, error) -> None: ...

    def list_sims(self, limit=20, run_id=None) -> list[dict]: ...

    def get_sim(self, run_id) -> dict | None: ...

    def latest_estimates(self) -> dict: ...

    def get_estimate(self, key, params_sha) -> dict | None: ...

    def put_estimate(self, key, params_sha, result) -> None: ...

    def stats(self) -> dict: ...

    def storage_status(self) -> dict: ...
