import type { ExtraOption, Scenario } from "./types";
export const defaultStudyFields = {
  arterial_lanes: 1,
  junction_control: "signal" as const,
  turn_share: 0,
  incident: null,
  extra_options: [] as ExtraOption[],
  clearance_reduction: 0.5,
  incident_weight: 1,
  signal_install_cost_cad: 250000,
  signal_removal_cost_cad: 30000,
  clearance_program_cost_cad: 50000,
  turn_lane_cost_cad: 400000,
  turn_ban_cost_cad: 10000,
};
export const defaults: Scenario = {
  main_vph: 1050,
  cross_vph: 160,
  duration_s: 900,
  seed: 42,
  budget_cad: 100000,
  cross_guardrail_pct: 30,
  retiming_cost_cad: 15000,
  widening_cost_cad: 1200000,
  annual_operating_cost_cad: 2000,
  occupancy: 1.2,
  value_of_time_cad: 20,
  operating_days: 250,
  asset_life_years: 10,
  demand_kind: "synthetic",
  demand_source: "Synthetic directional arrivals; not CalTRACS",
  flow_profile: null,
  ...defaultStudyFields,
};
