import { readFile, writeFile } from 'node:fs/promises';

// tokens.json is the source of truth. No package dependency or network required.
const directory = new URL('../src/design-tokens/', import.meta.url);
const tokens = JSON.parse(await readFile(new URL('tokens.json', directory), 'utf8'));
const kebab = name => name.replace(/[A-Z]/g, c => `-${c.toLowerCase()}`);
const declarations = [];
for (const [group, values] of Object.entries(tokens)) {
  for (const [name, value] of Object.entries(values)) {
    if (typeof value !== 'string' || /[;{}\n]/.test(value)) {
      throw new Error(`Invalid token: ${group}.${name}`);
    }
    declarations.push(`  --bb-${kebab(group)}-${kebab(name)}: ${value};`);
  }
}

function luminance(hex) {
  if (!/^#[0-9a-f]{6}$/i.test(hex)) throw new Error(`Invalid color: ${hex}`);
  const channels = [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map(c => c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  return channels[0] * 0.2126 + channels[1] * 0.7152 + channels[2] * 0.0722;
}
const pairs = [
  ['Body', 'ink', 'surface', 4.5], ['Muted', 'muted', 'surface', 4.5],
  ['Canvas body', 'ink', 'canvas', 4.5], ['Canvas muted', 'muted', 'canvas', 4.5],
  ['Navigation', 'navText', 'nav', 4.5], ['Primary action', 'onBrand', 'brand', 4.5],
  ['Primary hover', 'onBrand', 'brandHover', 4.5],
  ['Observed', 'observed', 'observedSurface', 4.5], ['Modeled', 'modeled', 'modeledSurface', 4.5],
  ['Assumed', 'assumed', 'assumedSurface', 4.5], ['Missing', 'missing', 'missingSurface', 4.5],
  ['Neutral', 'neutral', 'neutralSurface', 4.5],
  ['Focus on white', 'focus', 'surface', 3], ['Focus on canvas', 'focus', 'canvas', 3],
  ['Control border', 'borderStrong', 'surface', 3],
  ['Sidebar focus', 'onBrand', 'nav', 3],
  ['Sidebar selected focus', 'onBrand', 'navActive', 3],
  ...['chartBaseline', 'chartCandidate', 'chartRevision', 'chartCapacity']
    .map(key => [key, key, 'surface', 3])
];
const results = pairs.map(([label, foreground, background, minimum]) => {
  const a = luminance(tokens.color[foreground]);
  const b = luminance(tokens.color[background]);
  const ratio = (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);
  if (ratio < minimum) throw new Error(`${label}: ${ratio.toFixed(2)} < ${minimum}`);
  return { label, foreground, background, ratio: Number(ratio.toFixed(2)), minimum };
});
await writeFile(new URL('tokens.css', directory),
  `/* Generated by npm run tokens:build. Edit tokens.json, not this file. */\n:root {\n${declarations.join('\n')}\n}\n@media (prefers-reduced-motion: reduce) {\n  :root { --bb-motion-quick: 0ms; --bb-motion-normal: 0ms; }\n}\n`);
await writeFile(new URL('contrast-report.json', directory), `${JSON.stringify(results, null, 2)}\n`);
console.log(`Generated ${declarations.length} CSS tokens; ${results.length} contrast pairs passed.`);
